kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: busybox-pvc-smb
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: smb-csi