apiVersion: v1
kind: Service
metadata:
  name: gitea-frontend
  namespace: gitea
  labels:
    app.kubernetes.io/name: gitea
spec:
  type: LoadBalancer
  loadBalancerIP: "192.168.100.103"
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 2222
  selector:
    app: gitea
