apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-test-pod
  name: nginx-test-pod
spec:
  containers:
  - image: nginx
    name: nginx-test-pod
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 256Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always