apiVersion: storage.k8s.io/v1 # line:1144
kind: StorageClass
metadata:
  name: office-synology-csi-smb-del
  labels:
    vkube/storage-type: synology-csi-smb
provisioner: csi.san.synology.com
parameters: # https://github.com/SynologyOpenSource/synology-csi
  protocol: "smb"
  dsm: 192.168.100.227
  location: /volume3 # if blank, the CSI driver will choose a volume on DSM with available storage to create the volumes
  csi.storage.k8s.io/node-stage-secret-name: office-smb-secrets
  csi.storage.k8s.io/node-stage-secret-namespace: synology-csi
reclaimPolicy: Delete
allowVolumeExpansion: false
---
apiVersion: storage.k8s.io/v1 # line:1144
kind: StorageClass
metadata:
  name: office-synology-csi-smb-ret
  labels:
    vkube/storage-type: synology-csi-smb
provisioner: csi.san.synology.com
parameters: # https://github.com/SynologyOpenSource/synology-csi
  protocol: "smb"
  dsm: 192.168.100.227
  location: /volume3 # if blank, the CSI driver will choose a volume on DSM with available storage to create the volumes
  csi.storage.k8s.io/node-stage-secret-name: office-smb-secrets
  csi.storage.k8s.io/node-stage-secret-namespace: synology-csi
reclaimPolicy: Retain
allowVolumeExpansion: false
---
apiVersion: storage.k8s.io/v1 # line:1144
kind: StorageClass
metadata:
  name: office-synology-csi-smb-ret-exp
  labels:
    vkube/storage-type: synology-csi-smb
provisioner: csi.san.synology.com
parameters: # https://github.com/SynologyOpenSource/synology-csi
  protocol: "smb"
  dsm: 192.168.100.227
  location: /volume3 # if blank, the CSI driver will choose a volume on DSM with available storage to create the volumes
  csi.storage.k8s.io/node-stage-secret-name: office-smb-secrets
  csi.storage.k8s.io/node-stage-secret-namespace: synology-csi
reclaimPolicy: Retain
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1 # line:1166
kind: StorageClass
metadata:
  name: office-synology-csi-nfs-del
  labels:
    vkube/storage-type: synology-csi-nfs
provisioner: csi.san.synology.com
parameters: # https://github.com/SynologyOpenSource/synology-csi
  protocol: nfs
  dsm: "192.168.100.227"
  location: "/volume3" # if blank, the CSI driver will choose a volume on DSM with available storage to create the volumes
  mountPermissions: "0755"
mountOptions:
  - nfsvers=4
reclaimPolicy: Delete
allowVolumeExpansion: false
---
apiVersion: storage.k8s.io/v1 # line:1166
kind: StorageClass
metadata:
  name: office-synology-csi-nfs-ret
  labels:
    vkube/storage-type: synology-csi-nfs
provisioner: csi.san.synology.com
parameters: # https://github.com/SynologyOpenSource/synology-csi
  protocol: nfs
  dsm: "192.168.100.227"
  location: "/volume3" # if blank, the CSI driver will choose a volume on DSM with available storage to create the volumes
  mountPermissions: "0755"
mountOptions:
  - nfsvers=4
reclaimPolicy: Retain
allowVolumeExpansion: false
---
apiVersion: storage.k8s.io/v1 # line:1166
kind: StorageClass
metadata:
  name: office-synology-csi-nfs-ret-exp
  labels:
    vkube/storage-type: synology-csi-nfs
provisioner: csi.san.synology.com
parameters: # https://github.com/SynologyOpenSource/synology-csi
  protocol: nfs
  dsm: "192.168.100.227"
  location: "/volume3" # if blank, the CSI driver will choose a volume on DSM with available storage to create the volumes
  mountPermissions: "0755"
mountOptions:
  - nfsvers=4
reclaimPolicy: Retain
allowVolumeExpansion: true

