apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
namespace: development
resources:
  - ../../base
#patches:
#  - path: limits.yaml