apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
# https://kubernetes.io/docs/concepts/storage/volume-snapshot-classes/
metadata:
  name: synology-snapshotclass
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
driver: csi.san.synology.com
deletionPolicy: Delete
# parameters:
#   description: 'Kubernetes CSI' ＃ only for iscsi protocol
#   is_locked: 'false'