apiVersion: v1
kind: Service
metadata:
  name: longhorn-frontend
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn
spec:
  type: LoadBalancer
  loadBalancerIP: "192.168.100.101"
  ports:
  - name: http
    port: 80
    protocol: TCP
#    targetPort: 8080
#  - name: https
#    port: 443
#    protocol: TCP
#    targetPort: 8080
  selector:
    app: longhorn-ui
