apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
namespace: development
nameSuffix: "-test-001"
labels:
  - pairs:
      web: nginx
      ver: "test"
    includeSelectors: true
images:
  - name: nginx
    newName: nginx
    newTag: latest
resources:
  - ../../base
#patches:
#  - path: limits.yaml
