apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    spec:
      containers:
        - name: postgres
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"