apiVersion: storage.k8s.io/v1 # line:1202
kind: StorageClass
metadata:
  name: office-synology-csi-iscsi-tmp
  labels:
    vkube/storage-type: synology-csi-iscsi
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi.san.synology.com
parameters: # https://github.com/SynologyOpenSource/synology-csi
  protocol: iscsi
  dsm: "192.168.100.227"
  location: "/volume3" # if blank, the CSI driver will choose a volume on DSM with available storage to create the volumes
  csi.storage.k8s.io/fstype: btrfs
  formatOptions: --nodiscard
reclaimPolicy: Delete
allowVolumeExpansion: false
---
apiVersion: storage.k8s.io/v1 # line:1202
kind: StorageClass
metadata:
  name: office-synology-csi-iscsi-retain
  labels:
    vkube/storage-type: synology-csi-iscsi
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi.san.synology.com
parameters: # https://github.com/SynologyOpenSource/synology-csi
  protocol: iscsi
  dsm: "192.168.100.227"
  location: "/volume3" # if blank, the CSI driver will choose a volume on DSM with available storage to create the volumes
  csi.storage.k8s.io/fstype: ext4
  formatOptions: --nodiscard
reclaimPolicy: Retain
allowVolumeExpansion: false
---
apiVersion: storage.k8s.io/v1 # line:1232
kind: StorageClass
metadata:
  name: office-synology-csi-smb-tmp
  labels:
    vkube/storage-type: synology-csi-smb
provisioner: csi.san.synology.com
parameters: # https://github.com/SynologyOpenSource/synology-csi
  protocol: "smb"
  dsm: 192.168.100.227
  location: /volume3 # if blank, the CSI driver will choose a volume on DSM with available storage to create the volumes
  csi.storage.k8s.io/node-stage-secret-name: office-smb-secrets
  csi.storage.k8s.io/node-stage-secret-namespace: synology-csi
reclaimPolicy: Retain
allowVolumeExpansion: false
---
apiVersion: storage.k8s.io/v1 # line:1254
kind: StorageClass
metadata:
  name: office-synology-csi-nfs-retain
  labels:
    vkube/storage-type: synology-csi-nfs
provisioner: csi.san.synology.com
parameters: # https://github.com/SynologyOpenSource/synology-csi
  protocol: nfs
  dsm: "192.168.100.227"
  location: "/volume3" # if blank, the CSI driver will choose a volume on DSM with available storage to create the volumes
  mountPermissions: "0755"
mountOptions:
  - nfsvers=4
reclaimPolicy: Retain
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1 # line:1254
kind: StorageClass
metadata:
  name: backup2-synology-csi-nfs-retain
  labels:
    vkube/storage-type: synology-csi-nfs
provisioner: csi.san.synology.com
parameters: # https://github.com/SynologyOpenSource/synology-csi
  protocol: nfs
  dsm: "192.168.100.221"
  location: "/Volume1/csi-nfs" # if blank, the CSI driver will choose a volume on DSM with available storage to create the volumes
  mountPermissions: "0755"
mountOptions:
  - nfsvers=4
reclaimPolicy: Retain
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1 # line:1232
kind: StorageClass
metadata:
  name: backup2-synology-csi-smb-tmp
  labels:
    vkube/storage-type: synology-csi-smb
provisioner: csi.san.synology.com
parameters: # https://github.com/SynologyOpenSource/synology-csi
  protocol: "smb"
  dsm: 192.168.100.221
  location: /volume1 # if blank, the CSI driver will choose a volume on DSM with available storage to create the volumes
  csi.storage.k8s.io/node-stage-secret-name: backup2-smb-secrets
  csi.storage.k8s.io/node-stage-secret-namespace: synology-csi
reclaimPolicy: Retain
allowVolumeExpansion: true

