apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# kubectl apply -k ./
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
namespace: pgadmin
labels:
  - pairs:
      ver: "4"
    includeSelectors: true
images:
  - name: dpage/pgadmin4
    newTag: "latest"
resources:
  - ../../base
#patches:
#  - target:
#      kind: Service
#      name: pgadmin-balancer
#    patch: |
#      - op: replace
#        path: /spec/ports/0/port
#        value: 30100