apiVersion: v1
kind: Service
metadata:
  name: minio-frontend
  namespace: minio
  labels:
    app.kubernetes.io/name: minio
spec:
  type: LoadBalancer
  loadBalancerIP: "192.168.100.102"
  ports:
  - name: api
    protocol: TCP
    port: 9000
    targetPort: 9000
  - name: webui
    protocol: TCP
    port: 80
    targetPort: 9001
  selector:
    app: minio
