apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# kubectl apply -k ./
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/
namespace: mssql2019
namePrefix: mssql2019-
nameSuffix: "-master"
labels:
  - pairs:
      db: sqlserver
      ver: "15"
      sub: master
    includeSelectors: true
images:
  - name: mcr.microsoft.com/mssql/server
    newTag: "2019-latest"
resources:
  - ../../../base
  - svc.yaml
# patches:
#   - target:
#       kind: Service
#       name: mssql-balancer
#     patch: |
#       - op: replace
#         path: /spec/ports/0/port
#         value: 30219