apiVersion: v1
kind: Service
metadata:
  name: pihole-frontend
  namespace: pihole
  labels:
    app.kubernetes.io/name: pihole
spec:
  type: LoadBalancer
  loadBalancerIP: "192.168.100.111"
  ports:
  - name: http
    port: 80
    protocol: TCP
#    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
#    targetPort: 8080
  selector:
    app: pihole
