---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: office-csi-driver-smb-tmp-test-pvc
  namespace: storage-speedtest
spec:
  storageClassName: office-csi-driver-smb-tmp
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5G
---
apiVersion: batch/v1
kind: Job
metadata:
  name: office-csi-driver-smb-tmp-write-read
  namespace: storage-speedtest
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      name: office-csi-driver-smb-tmp-write-read
      namespace: storage-speedtest
      labels:
        app: office-csi-driver-smb-tmp-storage-speedtest
        job: write-read
    spec:
      containers:
      - name: write-read
        image: alpine:latest
        command: [sh, -c]
        args:
        - |
          echo 'alpine:'
          apk update
          apk add fio
          echo
          echo '###########################################'
          echo '# Storage class: office-csi-driver-smb-tmp'
          echo '###########################################'
          echo
          echo '=============== dd results ================'
          echo '  Sequential writing results:'
          dd if=/dev/zero of=/mnt/pv-office-csi-driver-smb-tmp/test.img bs=1G count=1 #oflag=dsync
          echo '  Sequential reading results:'
          # flush buffers or disk caches #
          #echo 3 | tee /proc/sys/vm/drop_caches
          dd if=/mnt/pv-office-csi-driver-smb-tmp/test.img of=/dev/null bs=8k
          echo
          echo '============== fio results ================'
          echo '-------------------------------------------'
          fio --name=test-write --direct=1 --rw=write --bs=1m --size=1g --numjobs=1 --time_based --runtime=10 --filename=/mnt/pv-office-csi-driver-smb-tmp/test.img
          echo '-------------------------------------------'
          fio --name=test-read --direct=1 --rw=read --bs=1m --size=1g --numjobs=1 --time_based --runtime=10 --filename=/mnt/pv-office-csi-driver-smb-tmp/test.img
          echo '-------------------------------------------'
          fio --name=test-randwrite-32k-1 --iodepth=1 --ioengine=libaio --direct=1 --rw=randwrite --bs=32k --size=1g --numjobs=1 --time_based --runtime=10 --filename=/mnt/pv-office-csi-driver-smb-tmp/test.img
          echo '-------------------------------------------'
          fio --name=test-randread-32k-1 --iodepth=1 --ioengine=libaio --direct=1 --rw=randread --bs=32k --size=1g --numjobs=1 --time_based --runtime=10 --filename=/mnt/pv-office-csi-driver-smb-tmp/test.img
          echo '-------------------------------------------'
          fio --name=test-randwrite-32k-4 --iodepth=4 --ioengine=libaio --direct=1 --rw=randwrite --bs=32k --size=1g --numjobs=1 --time_based --runtime=10 --filename=/mnt/pv-office-csi-driver-smb-tmp/test.img
          echo '-------------------------------------------'
          fio --name=test-randread-32k-4 --iodepth=4 --ioengine=libaio --direct=1 --rw=randread --bs=32k --size=1g --numjobs=1 --time_based --runtime=10 --filename=/mnt/pv-office-csi-driver-smb-tmp/test.img
          echo '-------------------------------------------'
          fio --name=test-randwrite-32k-16 --iodepth=16 --ioengine=libaio --direct=1 --rw=randwrite --bs=32k --size=1g --numjobs=1 --time_based --runtime=10 --filename=/mnt/pv-office-csi-driver-smb-tmp/test.img
          echo '-------------------------------------------'
          fio --name=test-randread-32k-16 --iodepth=16 --ioengine=libaio --direct=1 --rw=randread --bs=32k --size=1g --numjobs=1 --time_based --runtime=10 --filename=/mnt/pv-office-csi-driver-smb-tmp/test.img
          echo '-------------------------------------------'
          fio --name=test-randwrite-32k-64 --iodepth=64 --ioengine=libaio --direct=1 --rw=randwrite --bs=32k --size=1g --numjobs=1 --time_based --runtime=10 --filename=/mnt/pv-office-csi-driver-smb-tmp/test.img
          echo '-------------------------------------------'
          fio --name=test-randread-32k-64 --iodepth=64 --ioengine=libaio --direct=1 --rw=randread --bs=32k --size=1g --numjobs=1 --time_based --runtime=10 --filename=/mnt/pv-office-csi-driver-smb-tmp/test.img
          
        volumeMounts:
        - mountPath: "/mnt/pv-office-csi-driver-smb-tmp"
          name: test-volume-office-csi-driver-smb-tmp
      restartPolicy: Never
      volumes:
      - name: test-volume-office-csi-driver-smb-tmp
        persistentVolumeClaim:
          claimName: office-csi-driver-smb-tmp-test-pvc

