kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: office-synology-csi-smb-tmp-test-pvc
  namespace: storage-speedtest
spec:
  storageClassName: office-synology-csi-smb-tmp
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5G
---
apiVersion: batch/v1
kind: Job
metadata:
  name: office-synology-csi-smb-tmp-write-read
  namespace: storage-speedtest
spec:
  template:
    metadata:
      name: office-synology-csi-smb-tmp-write-read
      namespace: storage-speedtest
      labels:
        app: office-synology-csi-smb-tmp-storage-speedtest
        job: write-read
    spec:
      containers:
      - name: write-read
        image: ubuntu:xenial
        command: [sh, -c]
        args:
        - |
          # apt-get install -y iozone3
          # echo '  iozone -t1 -i0 -i2 -r1k -s1g -F /tmp/testfile:'
          # iozone -t1 -i0 -i2 -r1k -s1g -F /tmp/testfile
          echo '  Sequential writing results:'
          dd if=/dev/zero of=/mnt/pv/test.img bs=1G count=1 oflag=dsync
          echo '  Sequential reading results:'
          # flush buffers or disk caches #
          #echo 3 | tee /proc/sys/vm/drop_caches
          dd if=/mnt/pv/test.img of=/dev/null bs=8k
        volumeMounts:
        - mountPath: /mnt/pv
          name: test-volume
      volumes:
      - name: test-volume
        persistentVolumeClaim:
          claimName: office-synology-csi-smb-tmp-test-pvc
      restartPolicy: Never

