apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: devops-tools
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: jenkins-server
  type: LoadBalancer
  loadBalancerIP: "192.168.100.109"
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080

  # ports:
  #   - port: 8080
  #     targetPort: 8080
  #     nodePort: 32000