apiVersion: v1
kind: Service
metadata:
  name: jenkins-frontend
  namespace: jenkins
  labels:
    app.kubernetes.io/name: jenkins
spec:
  type: LoadBalancer
  loadBalancerIP: "192.168.100.109"
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins
