apiVersion: v1
kind: Service
# https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/
# https://kubernetes.io/docs/concepts/services-networking/service/
# https://v1-30.docs.kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/
# https://www.youtube.com/watch?v=T4Z7visMM4E
metadata:
  name: postgres-clusterip
  #labels:
  #  tier: clusterip
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: port
      port: 5432
      targetPort: 5432
---  
apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  #labels:
  #  tier: nodeport
spec:
  type: NodePort
  sessionAffinity: None
  ports:
    - name: postgresql
      port: 5432 # targetPort is same as port by default
      nodePort: 32000
      #targetPort: postgresql
      protocol: TCP
  #selector:
  #  tier: clusterip
---  
apiVersion: v1
kind: Service
metadata:
  name: postgres-balancer
spec:
#  selector:
#    tier: clusterip
    #workload.user.cattle.io/workloadselector: apps.deployment-dev-mssql2022
    #app: postgres
    #app: pg17-postgres-clusterip-001 # ????
  loadBalancerIP: "192.168.2.232"
  ports:
    - protocol: TCP
      name: port
      port: 32000
#      targetPort: 32000
  type: LoadBalancer