apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
spec:
  selector:
    matchLabels:
      app: mssql
  template:
    spec:
      containers:
        - name: mssql
          resources:
            limits:
              memory: "128Mi"
              cpu: "7000m"